version: '3.5'

services:
  daphne:
    container_name: django_rest
    build:
      context: ./adserver
      dockerfile: Dockerfile
    environment:
      - ADSERVER_SECRET_KEY=${ADSERVER_SECRET_KEY}
      - ADSERVER_DB_CONNECTION_NAME=${ADSERVER_DB_CONNECTION_NAME}
      - ADSERVER_DB_CONNECTION_USER=${ADSERVER_DB_CONNECTION_USER}
      - ADSERVER_DB_CONNECTION_PASSWORD=${ADSERVER_DB_CONNECTION_PASSWORD}
    ports:
      - "8000:8000"
    restart: always
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      backend:
    volumes:
      - django_data:/var/lib/adserver/data
    depends_on:
      - redis
  postgres:
    image: postgres:10
    environment:
      POSTGRES_USER: "${ADSERVER_DB_CONNECTION_USER}"
      POSTGRES_PASSWORD: "${ADSERVER_DB_CONNECTION_PASSWORD}"
      POSTGRES_DB: "${ADSERVER_DB_CONNECTION_NAME}"
    ports:
      - "5432"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      backend:
  vue:
    container_name: front
    build:
      context: ./adserver-vue
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      frontend:
    volumes:
      - '.:/adserver-app'
      - '/adserver-app/node_modules'
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      backend:
    volumes:
      - '.:/redis_data'
networks:
    backend:
    frontend:
volumes:
  db-data:
  django_data: 